#!/bin/sh

pgsql2shp -p 15432 -f counties.shp usa "select geom,geoid10 as geoid from counties"
topojson -p \
  --id-property geoid=GEOID \
  --external-properties data/cfb-counties.csv \
  --no-pre-quantization \
  --post-quantization=1e6 \
  --simplify=7e-7 \
  counties.shp > data/us-counties.json
