#!/usr/bin/env ruby

require 'csv'
require 'pg'

conn = PG.connect(:dbname => 'nhgis')
codes = {}

mappings = {
  'Chestnut Hill:25'   => 'Boston',
  'Honolulu:15'        => 'Urban Honolulu',
  'Athens:13'          => 'Athens-Clarke County unified government (balance)',
  'University Park:42' => 'State College',
  'Boise:16'           => 'Boise City',
  'Lexington:21'       => 'Lexington-Fayette',
  'Piscataway:34'      => 'New Brunswick',
  'Louisville:21'      => 'Louisville/Jefferson County metro government (balance)',
  'Amherst:36'         => 'Williamsville',
  'Nashville:47'       => 'Nashville-Davidson metropolitan government (balance)'
}

CSV.foreach('data/statecodes.csv', :headers => true) do |state|
  codes[state['abbr']] = state['fips']
end

csv = CSV.open('data/stadiums.csv', 'a',
  :headers => 'stadium,city,state,team,conference,capacity,record,built,expanded,place_gid,statefp,placefp'.split(','),
  :write_headers => true)

CSV.foreach('data/football-stadiums.csv', :headers => true) do |row|
  fips = codes[row['state'].downcase]
  city = row['city']
  city = mappings[city + ":#{fips}"] if !mappings[city + ":#{fips}"].nil?
  row['capacity'] = row['capacity'].gsub(',', '').to_i if row['capacity']
  row['record'] = row['record'].gsub(',', '').to_i if row['record']

  conn.exec('SELECT gid, name, statefp, placefp from nhgis_places WHERE name=$1 AND statefp=$2', [city, fips]) do |result|
    record = result.first
    vals = row.to_hash.values
    vals.pop
    vals += [record['gid'], record['statefp'], record['placefp']]
    csv << vals
  end
end

csv.close
