#!/bin/sh
#
# Example:
#
#   $ ./bin/recruits2pgsql -d sports -c data/recruits.csv
#
usage() { echo "Usage: $0 [-d postgres database] [-c csv file]" 1>&2; exit 1; }

while getopts ":d:c:" opt; do
  case $opt in
    d)
      dbname=$OPTARG
      ;;
    c)
      csv_dir=$OPTARG
      ;;
    *)
      usage
      ;;
  esac
done

shift $((OPTIND-1))

if [ -z "${dbname}" ] || [ -z "${csv_dir}" ]; then
  usage
fi

dropdb --if-exists --interactive -e $dbname
createdb --template template0 --encoding UTF8 $dbname

psql -d $dbname -c 'create extension postgis'
psql -d $dbname -c 'drop table if exists recruits'
psql -d $dbname -f sql/recruit-schema.sql
psql -d $dbname -f sql/point-in-polygon.sql

cat data/csv/combined.csv | psql -d $dbname -c "copy recruits from stdin with csv header"
psql -c "create index recruits_stars on recruits (stars)" $dbname
psql -c "create index recruits_region on recruits (region)" $dbname

psql -c "alter table recruits add column geom geometry(Point,4326)" $dbname
psql -c "update recruits set geom = st_setsrid(st_makepoint(lng, lat), 4326)" $dbname
psql -c "create index recruits_gix on recruits using gist (geom)" $dbname
